spring:
  profiles:
    active: dev
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:shedlock_DB
    username: sa
    password:
  application:
    name: shedlock-spboot-app
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  sql:
    init:
      mode: always
      platform: h2
  h2:
    console:
      enabled: true
      path: /h2
logging:
  level:
    root: info
    net.javacrumbs.shedlock: debug
    sql: debug
